### ISSUE TITLE
Currently not possible to install onto Macs with new Apple Silicon chips

### ISSUE THREAD

**Issue by dovidel** [DavisLaboratory/msImpute#3]
I have been trying to install this package using R-4.3.2 (for Macs with Apple Silicon M1/M2 chips), and have been having some difficulty. It seems that this package cannot be installed since one of the depedencies scran (https://bioconductor.org/packages/release/bioc/html/scran.html) does not have a binary source availble for macOS Binary (arm64). Is there any way we can install this package without scran, or do we just need to wait until the developers of scran update their package? I would totally understand if this issue is out of your hands.

**Comment by soroorh** [comment]
Hey 
Thanks for using issue tracker. I've dropped scran dependency for v1.12.0 [here](https://github.com/DavisLaboratory/msImpute/tree/1.12.0).  As the result of this, `findVariableFeatures` function was removed, so it can no longer be used with this version (and is not really part of the most recent workflow). Can you please install from source and let me know if that works? thx

**Comment by dovidel** [comment]
I tried downloading scran from the source using `git clone https://git.bioconductor.org/packages/scran` and then turning it into a .tar.gz folder using `tar czf scran.tar.gz scran` in the terminal, and then tried to from the package archive using RStudio's install packages functionality, but this also did not work. I apologize for my lack of knowledge in this particular area, but is this the right approach for installing from the source? 

Furthermore, I tried to install msImpute on a different Mac with R version 4.1.1 that had an OS version 11.6 and a 3.5 GHz Intel Xeon processor, and it also yielded a variety of errors, some of which seem to be related to dplyr, freetype2, and libpng, among others. I'm sorry, but I could not get the full error traceback at this time. If you want me to get it, please let me know.

**Comment by soroorh** [comment]
Apologies for miscommunication. I actually meant installing msimpute from source. So, please clone the version on the [branch](https://github.com/DavisLaboratory/msImpute/tree/1.12.0) and run 

```
install.packages("/path to folder with the package", 
repos = NULL, 
type = "source")
```

Hope this helps.

**Comment by dovidel** [comment]
@soroorh thanks so much! It seems to work now that I used the branch 1.12.0.
